using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SalesManagmentSystem2.DAL.Models;
using SalesManagmentSystem2.DAL.DbInventory;
using SalesManagmentSystem2.PL;
using System.Windows.Controls;
using DevExpress.XtraGrid.Views.Grid;
using GridView = DevExpress.XtraGrid.Views.Grid.GridView;

namespace SalesManagmentSystem2
{
    public partial class FrmCategories : Form
    {
        GridView grid;
        InventoryDB db = new InventoryDB();
        bool flag = false;
        private Category selectedcategory = null;
        MessageDialog messageDialog = new MessageDialog();
        public FrmCategories()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SalesManagmentSystem2.DAL.DbInventory.InventoryDB dbContext = new SalesManagmentSystem2.DAL.DbInventory.InventoryDB();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Categories.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
                categoriesBindingSource.DataSource = dbContext.Categories.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            //grid.FocusedRowChanged += (sender, e) => selectedcategory = ((Category)grid.GetFocusedRow());

        }
        private void pnlCat_Paint(object sender, PaintEventArgs e)
        {

        }

        private void FrmCategories_Load(object sender, EventArgs e)
        {
            

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            
            if(!flag)
            {

                Category category = new Category();
                category.CatName = textBox1.Text;
                if(textBox1.Text=="")
                {
                    MessageBox.Show("ن فضلك ادخل اسم الصنف");
                }
                db.Categories.Add(category);
                db.SaveChanges();
            }
            MessageBox.Show("تم اضافة الصنف بنجاح");

            db.Categories.Load();
            reset();
            gridControl1.DataSource=db.Categories.Local.ToBindingList();
           
        }



        private void btnEdit_Click(object sender, EventArgs e)
        {
            int iid = Convert.ToInt32(gridView1.GetFocusedRowCellValue("CatID"));
            if(selectedcategory!=null)
            {
                if (!flag)
                {
                    FilltxtOnSelectesData(selectedcategory);
                    btnEdit.Text = "حفظ التعديلات";
                    flag = true;
                }
                else if (flag)
                {
                    messageDialog.Message = "هل انت متأكد من تعديل هذا الصنف!";

                    if (messageDialog.ShowDialog() == DialogResult.Yes)
                    {
                        Category category = db.Categories.Where(id => id.CatID == selectedcategory.CatID).FirstOrDefault();
                        category.CatName = textBox1.Text;
                        db.Entry(category).State = EntityState.Modified;
                        db.SaveChanges();
                        MessageBox.Show("تم التعديل بنجاح");

                    }
                    btnEdit.Text = "تعديل";
                }
            }
        }


        private void btnDelete_Click(object sender, EventArgs e)
        {
            messageDialog.Message = "هل انت متاكد ان تريد مسح هذا العميل";
            if (selectedcategory != null)
            {
                if (messageDialog.ShowDialog() == DialogResult.Yes)
                {
                    db.Entry(selectedcategory).State = EntityState.Deleted;
                    db.SaveChanges();
                }
                reset();
            }
        }


        //reset Values
        private void reset()
        {
            textBox1.Text = "";
            flag = false;
        }

        //fill text with selected category data
        private void FilltxtOnSelectesData(Category category)
        {
            textBox1.Text = category.CatName;

        }
    }
}
