using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SalesManagmentSystem2
{
    public partial class Purchasing_invoice : Form
    {
        public Purchasing_invoice()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            purchasing_invoiceTableAdapter1.Fill(inventoryMSDbDataSet81.Purchasing_invoice);
        }

        private void Purchasing_invoice_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'inventoryMSDbDataSet8.Purchasing_invoice' table. You can move, or remove it, as needed.
            this.purchasing_invoiceTableAdapter.Fill(this.inventoryMSDbDataSet8.Purchasing_invoice);

        }
    }
}
